name: CI/CD Pipeline

on:
  push:
    branches: [master, enhancement/**]
  pull_request:
    branches: [master, enhancement/**]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ruff Linter
        run: ruff check .

      - name: Run unit tests with coverage
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest --cov=app --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        if: success()
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-ml-app:latest .

      - name: Push Docker image to Docker Hub
        if: success()
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-ml-app:latest
